### ISSUE TITLE
Can't use as npm module

### ISSUE THREAD

**Issue by subdesign** [hootlex/vuejs-paginator#13]
I want to use vuejs-paginator for my project, with Laravel 5.3, but when I _import_ it, running __gulp__ I have the following errors:
```
Browserify Failed!: Cannot find module '-!vue-html-loader!./../node_modules/vue-loader/lib/selector.js?type=template&index=0!./VPaginator.vue' from '/var/www/vuejs.app/node_modules/vuejs-paginator/dist' 
```
and
```
Browserify Failed!: Cannot find module '-!babel!./../node_modules/vue-loader/lib/selector.js?type=script&index=0!./VPaginator.vue' from '/var/www/vuejs.app/node_modules/vuejs-paginator/dist'
```
babel and vue-html-loader npm moduls are installed of course..

Vue.js 1.0.28
vuejs-paginator: 1.0.13

The only good part of the story, using the CDN version of vuejs-paginator I have no problems, my code runs well. But I want to compile the modules and have one file at the end!

**Comment by subdesign** [comment]
Found the other issue for the solution, that works. Thanks

**Comment by sirsquall** [comment]
What what was the solution? I have exactly the same issue.
