### ISSUE TITLE
Basic setup

### ISSUE THREAD

**Issue by maciej-bielski** [hootlex/vuejs-paginator#17]
Hello,

first I'd like to thank you for your work. Pagination is intuitive, documentation is great and available options are well thought out.

I'm backend dev learning how to do frontend and although documentation is just great I cannot figure out how to setup basic project with just one component e.g. Listing which will use uvejs-paginator. 

I think that it would be great to add zip file to http://hootlex.github.io/vuejs-paginator/ with package.json, app.js, Listing.vue etc. (minimal setup). This approach would help lots of users :)

I'm using gulp with laravel-elixir and laravel-elixir-vue-2. I've got error with missing vue-html-loader. 

One more time thanks for your contribution in Vue world :)

**Comment by hootlex** [comment]
Hello @maciej-bielski and thank you for the kind words.
Have you managed to solve it?

**Comment by kodekrendel** [comment]
> documentation is great

What documentation? There's literally no documentation.
