### ISSUE TITLE
Is there github code for the animal example?

### ISSUE THREAD

**Issue by kenpeter** [hootlex/vuejs-paginator#20]
Hi,
Where can I find the full source code (front + back) for the animal example? A working example project will be good.

**Comment by hootlex** [comment]
Hey, the doc's example is in the [gh-pages branch](https://github.com/hootlex/vuejs-paginator/tree/gh-pages) of the repo.

**Comment by kodekrendel** [comment]
@hootlex there's 3 hardcoded json files there. That's cheating. Does this plugin fetch the data from SINGE file, or do I manually have to do that? Why then you put that in exampe? Why it's not single json file?

**Comment by hootlex** [comment]
@kodekrendel The 3 hardcoded files you mention are a mock of an API. The purpose of this plugin is to help you work with data coming from APIs.
