### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by kodekrendel** [hootlex/vuejs-paginator#22]
I use `<v-paginator resource_url="api/animals" @update="updateResource"></v-paginator>`

Then it says `Thats it` and next code is following, which is little confusing 
```
<ul>
  <li v-for="animal in animals">
    {{ animal.name }}
  </li>
</ul>
```
Do I need `Thats it` part? 

Also I wonder, did somebody test it with SSR/Nuxt?

**Comment by codw99** [comment]
You need add a `updateResource` in your methods

```js
updateResource: function (data) {
     console.log(data)
     //this.animals = data
}
```
