### ISSUE TITLE
button text option doesn't set

### ISSUE THREAD

**Issue by rowej83** [hootlex/vuejs-paginator#3]
previous_button_text & next_button_text value doesn't change even after you pass it in options

**Comment by hootlex** [comment]
I've just checked it and it works as expected.
Maybe you are not passing the `options` properly.
Check [this](https://jsfiddle.net/hootlex/o380xqoL/2/).

**Comment by rowej83** [comment]
Your right. I had an error on my part. closing issue

**Comment by hootlex** [comment]
Great!
