### ISSUE TITLE
Options are seem to be ignored

### ISSUE THREAD

**Issue by atleta** [hootlex/vuejs-paginator#31]
Hi,

I wasn't able to override the default data properties (prev/next link, data, etc. names) using the options (on the enclosing component) as described in the document. Curiously, the Authorization header went through, but after looking at the code, I wasn't able to find how and why. Anyway, the above doesn't seem to work.

**Comment by hootlex** [comment]
Hi @atleta, please provide a way to reproduce.
A jsfiddle or a codepen would be great.
