### ISSUE TITLE
npm run build error with UglifyJs

### ISSUE THREAD

**Issue by cnweibo** [hootlex/vuejs-paginator#7]
`
$ npm run build

> vuejs-paginator@1.0.15 build C:\Users\Administrator\devenvironment\Code\newkidsitfromscratch\resources\assets\js\vueapp\node_modules\vuejs-paginator
> webpack --progress --hide-modules --config  webpack.build.min.js && webpack --progress --hide-modules --config  webpack.build.js
                                                                                                        Hash: 385d317dedc2ff8c3e78
Version: webpack 1.13.2
Time: 93ms
                        Asset     Size  Chunks             Chunk Names
./dist/vuejs-paginator.min.js  1.84 kB       0  [emitted]  vuejs-paginator

ERROR in ./dist/vuejs-paginator.min.js from UglifyJs
SyntaxError: Unexpected token: name (VPaginator) [./dist/vuejs-paginator.min.js:57,8]                   Hash: 7dbe773c9039f0780d69
Version: webpack 1.13.2
Time: 92ms
                        Asset     Size  Chunks             Chunk Names
    ./dist/vuejs-paginator.js  1.98 kB       0  [emitted]  vuejs-paginator
./dist/vuejs-paginator.js.map  2.27 kB       0  [emitted]  vuejs-paginator
`

**Comment by hootlex** [comment]
It works fine for me. What's your npm version?

**Comment by cnweibo** [comment]
Sorry, i can not figure it out now.
But i know the vue-paginator should be updated due to vuejs2.0 officially available now. And it does not work compatible to vuejs2.0.

**Comment by hootlex** [comment]
Vue.js Paginated 2.0 is compatible with Vue 2.
