### ISSUE TITLE
How to refresh manually

### ISSUE THREAD

**Issue by nicozimmermann94** [hootlex/vuejs-paginator#8]
Hey, is it possible to refresh the data source manually?

**Comment by hootlex** [comment]
You mean to manually change the current page?

**Comment by nicozimmermann94** [comment]
No, I mean how to invoke the fetchData() methode manually.
Whenever I change the url, the paginator reloads the data. This is fine but I also need a way to manually reload the data, because they changed on the server side.

**Comment by hootlex** [comment]
Currently, this is not possible.
However, I will update the plugin to be compatible with Vue 2 soon. I will add this feature then too.

**Comment by hootlex** [comment]
V2 is out. Check [this](http://hootlex.github.io/vuejs-paginator/#fetch-data-manually). :)

**Comment by nicozimmermann94** [comment]
Thank you very much!

**Comment by 0xLuz** [comment]
@nicozimmermann94 did you get to implemented it? could you provide an example? I would like to use static/raw data instead of consuming an api, but I couldn't understand the docs about how to fetch data manually.
